import custom_classes.FrameUtils;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Kai Jie
 */
public class MainLauncher extends javax.swing.JFrame {
    final private LoginFrame loginFrame;    
    final private GameLevelFrame gamelevelFrame;    
    final private PuzzleFrame puzzleFrame;    
    final private SignUpFrame signUpFrame;    
    final private ScoreFrame scoreFrame;
    public String userFirstName, userLastName, userEmail;
    private final String demo = "Demo";

    /**
     * Creates new form MainLauncher
     */
    public MainLauncher() {
        initComponents();
        
        // Use the utility method to set title and icon
        FrameUtils.setFrameTitleAndIcon(this, "PuzzlePath 15", "/resources/15.png");
        
        gamelevelFrame = new GameLevelFrame(this);
        puzzleFrame = new PuzzleFrame(this, demo, gamelevelFrame);        
        loginFrame = new LoginFrame(this);        
        signUpFrame = new SignUpFrame(this);        
        scoreFrame = new ScoreFrame(this);

        btn_play.setVisible(false);        
        lbl_user.setVisible(false);

        FrameUtils.addHoverEffect(btn_demo);
        FrameUtils.addHoverEffect(btn_login);        
        FrameUtils.addHoverEffect(btn_play);
        FrameUtils.addHoverEffect(btn_score);        
        FrameUtils.addHoverEffect(btn_exit);

    }
    
    public void setUserName(String fname, String lname) {
        this.userFirstName = fname;
        this.userLastName = lname;
        updateUIAfterLogin();
    }

    public String getUserFirstName() {
        return userFirstName;
    }
    
    public String getUserLastName() {
        return userLastName;
    }
    
    public void setUserEmail(String email) {
        this.userEmail = email;
    }
    
    public String getUserEmail() {
        return userEmail;
    }
    
    private void updateUIAfterLogin() {
        btn_login.setVisible(false);
        btn_sign.setVisible(false);
        btn_play.setVisible(true);
        
        lbl_guest.setVisible(false);
        lbl_user.setVisible(true);
        lbl_user.setText("Welcome "+ getUserFirstName() +" "+getUserLastName());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_user = new javax.swing.JLabel();
        lbl_guest = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();
        btn_demo = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_sign = new javax.swing.JButton();
        btn_login = new javax.swing.JButton();
        btn_play = new javax.swing.JButton();
        btn_score = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_user.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_user.setForeground(new java.awt.Color(51, 255, 204));
        lbl_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_user.setText("Welcome Logged In User 1234567890");
        getContentPane().add(lbl_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 470, -1));

        lbl_guest.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_guest.setForeground(new java.awt.Color(51, 255, 51));
        lbl_guest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_guest.setText("Welcome Guest");
        getContentPane().add(lbl_guest, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        lbl_title.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 0));
        lbl_title.setText("PuzzlePath 15");
        getContentPane().add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 50, 320, -1));

        btn_demo.setBackground(new java.awt.Color(255, 153, 51));
        btn_demo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_demo.setForeground(new java.awt.Color(51, 0, 0));
        btn_demo.setText("DEMO");
        btn_demo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_demoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_demo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 150, 50));

        btn_exit.setBackground(new java.awt.Color(255, 153, 51));
        btn_exit.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(51, 0, 0));
        btn_exit.setText("EXIT");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 150, 50));

        btn_sign.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_sign.setForeground(new java.awt.Color(51, 0, 0));
        btn_sign.setText("SIGN UP");
        btn_sign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sign, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 120, 30));

        btn_login.setBackground(new java.awt.Color(255, 153, 51));
        btn_login.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_login.setForeground(new java.awt.Color(51, 0, 0));
        btn_login.setText("LOGIN");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 150, 50));

        btn_play.setBackground(new java.awt.Color(255, 153, 51));
        btn_play.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_play.setForeground(new java.awt.Color(51, 0, 0));
        btn_play.setText("PLAY");
        btn_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_playActionPerformed(evt);
            }
        });
        getContentPane().add(btn_play, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 150, 50));

        btn_score.setBackground(new java.awt.Color(255, 153, 51));
        btn_score.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_score.setForeground(new java.awt.Color(51, 0, 0));
        btn_score.setText("SCORE BOARD");
        btn_score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_scoreActionPerformed(evt);
            }
        });
        getContentPane().add(btn_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 150, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/main_bg.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, -1));

        jMenu1.setText("Menu");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/menu.png"))); // NOI18N
        jMenuItem1.setText("Home");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/close.png"))); // NOI18N
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        FrameUtils.goToFrame(this, loginFrame);
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_signActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signActionPerformed
        FrameUtils.goToFrame(this, signUpFrame);
    }//GEN-LAST:event_btn_signActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_demoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_demoActionPerformed
        FrameUtils.goToFrame(this, puzzleFrame);
    }//GEN-LAST:event_btn_demoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btn_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_playActionPerformed
        FrameUtils.goToFrame(this, gamelevelFrame);
    }//GEN-LAST:event_btn_playActionPerformed

    private void btn_scoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_scoreActionPerformed
        scoreFrame.loadScores();
        FrameUtils.goToFrame(this, scoreFrame);
    }//GEN-LAST:event_btn_scoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainLauncher().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_demo;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_play;
    private javax.swing.JButton btn_score;
    private javax.swing.JButton btn_sign;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lbl_guest;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_user;
    // End of variables declaration//GEN-END:variables
}
